### ISSUE TITLE
Option to change color

### ISSUE THREAD

**Issue by forivall** [yifu/highlight-trailing-whitespaces#5]
I'd like it to be yellow, as trailing whitespace is significant in markdown. (i'm willing to submit a pr too!)

**Comment by yifu** [comment]
Sorry for the late reply. I'm open to PR. I am no longer maintaining the extension nor using it.

**Comment by forivall** [comment]
cool. if i figure it's important enough (as in, if i'm authoring markdown enough for it to be useful again), i'll probably just use it as a base for a new extension then (thanks for unlicensing ❤️ )
